name: CI/CD Test

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup Terraform
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Install terraform
        id: install
        env:
          TF_VERSION: "1.3.6"
        run: |
          wget "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
          unzip terraform_${TF_VERSION}_linux_amd64.zip
          sudo mv terraform /usr/local/bin

  terraform_init:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init

  terraform_plan:
    runs-on: ubuntu-latest
    needs:
      - terraform_init
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Terraform Plan
        run: terraform plan

  terraform_apply:
    runs-on: ubuntu-latest
    needs:
      - terraform_plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Wait for approval
        run: echo "Waiting for manual approval..."
      # Aquí es donde se requiere la aprobación manual
      # Puedes usar un comentario para indicar que se debe aprobar
      - name: Request Manual Approval
        id: approval
        run: echo "Approve this workflow by commenting '/approve' on the pull request."
      
  manual_approval:
    needs: terraform_apply
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.body, '/approve')
    steps:
      - name: Manual approval granted
        run: echo "Manual approval granted. Running Terraform Apply."
        # Aquí es donde puedes ejecutar el terraform apply