name: CI/CD Test

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup Terraform
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Install terraform
        id: install
        env:
          TF_VERSION: "1.3.6"
        run: |
          echo "Instala terraform"

  terraform_init:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Terraform Init
        run:
          echo "corre Terraform init"
          # terraform init

  terraform_plan:
    runs-on: ubuntu-latest
    needs:
      - terraform_init
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Terraform Plan
        run:
          echo "Corre terraform plan"
          # terraform plan

  terraform_apply:
    runs-on: ubuntu-latest
    needs:
      - terraform_plan
    environment:
        name: env
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Terraform Apply
        run: echo "Corre terraform apply"
